version: '3.8'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=es-docker-twitter
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - prometheus-data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"

    logstash:
        image: docker.elastic.co/logstash/logstash:7.13.0
        container_name: logstash
        volumes:
            - type: bind
              source: ./logstash/config/logstash.yml
              target: /usr/share/logstash/config/logstash.yml
              read_only: true
            - type: bind
              source: ./logstash/pipeline
              target: /usr/share/logstash/pipeline
              read_only: true
        ports:
            - "5044:5044"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        depends_on:
            - elasticsearch

    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.0
        container_name: kibana
        volumes:
            - type: bind
              source: ./kibana/config/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        ports:
            - "5601:5601"
        depends_on: 
            - elasticsearch
    
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports: 
            - "3000:3000"
        volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        env_file:
            - ./grafana/.env

    twitterapi:
        image: brunocaleffi/twitter-api:v1.0.0
        container_name: twitterapi
        env_file: ./.env
        ports: 
            - "5000:5000"
        depends_on: 
            - logstash

volumes:
    prometheus-data:
        driver: local
    grafana-data:
        driver: local